### ISSUE TITLE
:rdgen fails "NoSuchMethod getNlsString" 

### ISSUE THREAD

**Issue by benjamin-asdf** [JetBrains/resharper-rider-plugin#40]
I can reproduce it by 

```
dotnet new resharper-rider-plugin --name BestResharper --include-samples
cd BestResharper
gradle :rdgen
```

```
> Task :rdgen
Reading hash from /home/benj/repos/kotlin/BestResharper/build/.rdgen
Hashes are different at key 'file: /home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.rd/rd-gen/0.211.235/c208e05c251ac636b4179151d770ca95b6ad5f22/rd-gen-0.211.235.jar', oldHash: , newHash:2021-08-04_15:53:57.352
Temporary folder created: /tmp/rdgen-15010838409650662933
Searching for Kotlin compiler
Compiling sources from '/home/benj/repos/kotlin/BestResharper/protocol/src/main/kotlin/model/rider' to '/tmp/rdgen-15010838409650662933'
User classpath: '/home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.2/a9ef7670ed1ce9867cfdf6dfc73782362db29322/riderRD-2021.2/lib/rd/rider-model.jar'
Rdgen default classpath: '/home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.rd/rd-gen/0.211.235/c208e05c251ac636b4179151d770ca95b6ad5f22/rd-gen-0.211.235.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.0/e5f0d669a77787ccbccd49c71b57bfd7b35faec4/kotlin-compiler-embeddable-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.0/aa2101a19d8688e368ae6e35e8967550ced73884/kotlin-reflect-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.0/1c752cce0ead8d504ccc88a4fed6471fd83ab0dd/kotlin-stdlib-common-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.0/52ac54a56c9121f54fcca387c5a0f441d1af9be8/kotlin-script-runtime-1.4.0.jar'
Resulting kotlinc classpath: '/home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.2/a9ef7670ed1ce9867cfdf6dfc73782362db29322/riderRD-2021.2/lib/rd/rider-model.jar:/home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.rd/rd-gen/0.211.235/c208e05c251ac636b4179151d770ca95b6ad5f22/rd-gen-0.211.235.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.0/e5f0d669a77787ccbccd49c71b57bfd7b35faec4/kotlin-compiler-embeddable-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.0/aa2101a19d8688e368ae6e35e8967550ced73884/kotlin-reflect-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.0/1c752cce0ead8d504ccc88a4fed6471fd83ab0dd/kotlin-stdlib-common-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.0/52ac54a56c9121f54fcca387c5a0f441d1af9be8/kotlin-script-runtime-1.4.0.jar'
kotlinc -cp /home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.2/a9ef7670ed1ce9867cfdf6dfc73782362db29322/riderRD-2021.2/lib/rd/rider-model.jar:/home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.rd/rd-gen/0.211.235/c208e05c251ac636b4179151d770ca95b6ad5f22/rd-gen-0.211.235.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.0/e5f0d669a77787ccbccd49c71b57bfd7b35faec4/kotlin-compiler-embeddable-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.0/aa2101a19d8688e368ae6e35e8967550ced73884/kotlin-reflect-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.0/1c752cce0ead8d504ccc88a4fed6471fd83ab0dd/kotlin-stdlib-common-1.4.0.jar:/home/benj/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.0/52ac54a56c9121f54fcca387c5a0f441d1af9be8/kotlin-script-runtime-1.4.0.jar -no-stdlib -d /tmp/rdgen-15010838409650662933 -jvm-target 1.8 /home/benj/repos/kotlin/BestResharper/protocol/src/main/kotlin/model/rider
Compilation finished in 2341 ms
Loading compiled classes from 'file:/tmp/rdgen-15010838409650662933/, file:/home/benj/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.rider/riderRD/2021.2/a9ef7670ed1ce9867cfdf6dfc73782362db29322/riderRD-2021.2/lib/rd/rider-model.jar'
gradleGenerationSpecs=[GenerationSpec(language=kotlin, transform=asis, root=com.jetbrains.rider.model.nova.ide.IdeRoot, namespace=com.jetbrains.rider.model, directory=/home/benj/repos/kotlin/BestResharper/src/rider/main/kotlin/com/jetbrains/rider/plugins/bestresharper, generatedFileSuffix=.Generated)
GenerationSpec(language=csharp, transform=reversed, root=com.jetbrains.rider.model.nova.ide.IdeRoot, namespace=JetBrains.Rider.Model, directory=/home/benj/repos/kotlin/BestResharper/src/dotnet/ReSharperPlugin.BestResharper/Rider, generatedFileSuffix=.Generated)]
noLineNumbersInComments=false

RdGen model generator started
Searching classes with namespace prefixes: 'model.rider'
Regex for filtering generators: '.*'
Found 2 gradle generators
3 classes found
1 toplevel class found

Toplevels to generate:
  singleton `BestResharperModel` :> concrete_class `Solution` :> singleton `SolutionModel` :> root `IdeRoot`
java.lang.NoSuchMethodError: 'com.jetbrains.rd.generator.nova.ScalarAttributedType com.jetbrains.rd.generator.nova.FunctionsKt.getNlsString()'
	at com.jetbrains.rider.model.nova.ide.SolutionModel$RdTextChunk$1.invoke(SolutionModel.kt:99)
	at com.jetbrains.rider.model.nova.ide.SolutionModel$RdTextChunk$1.invoke(SolutionModel.kt:13)
	at com.jetbrains.rd.generator.nova.Declaration.initialize(Types.kt:224)
	at com.jetbrains.rd.generator.nova.Root.initialize(Types.kt:561)
	at com.jetbrains.rd.generator.nova.GenerateKt.generateRdModel(generate.kt:43)
	at com.jetbrains.rd.generator.nova.RdGen$run$outputFolders$1.invoke(RdGen.kt:303)
	at com.jetbrains.rd.generator.nova.RdGen$run$outputFolders$1.invoke(RdGen.kt:18)
	at com.jetbrains.rd.generator.nova.util.EnvUtilKt.usingSystemProperty(EnvUtil.kt:34)
	at com.jetbrains.rd.generator.nova.RdGen.run(RdGen.kt:299)
	at com.jetbrains.rd.generator.nova.MainKt.main(Main.kt:8)

> Task :rdgen FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rdgen'.
> Process 'command '/usr/lib/jvm/java-16-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
```

Should be with the latest version.

**Comment by ForNeVeR** [comment]
I think that the issue should be resolved by updating rdgen to a newer version. The one used in the template is pretty old.

**Comment by benjamin-asdf** [comment]
```    id 'org.jetbrains.kotlin.jvm' version '1.5.10'
```

btw I also got errors when compiling kotlin and putting this version fixed it

**Comment by matkoch** [comment]
- Update of rd-gen was broken after the way of reference changed – fixed
- Added update of Kotlin JVM for next releases

Thanks for bringing this up!
